-- Supabase CLI scaffold generated by migration new on 2026-10-01 and adapted to the existing bot/migrations chain.
-- Additive public request idempotency: no stored rows or RLS policies are rewritten.
BEGIN;

ALTER TABLE public.public_discovery_requests
    ADD COLUMN IF NOT EXISTS request_idempotency_key UUID;

CREATE UNIQUE INDEX IF NOT EXISTS idx_public_discovery_requests_idempotency_key
    ON public.public_discovery_requests(request_idempotency_key)
    WHERE request_idempotency_key IS NOT NULL;

COMMENT ON COLUMN public.public_discovery_requests.request_idempotency_key
    IS 'Opaque client retry key; not readable by browser roles and never included in operator notification text.';

CREATE OR REPLACE FUNCTION public.submit_public_discovery_request_internal(
    p_request_type TEXT,
    p_subject TEXT,
    p_details TEXT,
    p_idempotency_key UUID DEFAULT NULL,
    p_listing_type TEXT DEFAULT NULL,
    p_location TEXT DEFAULT NULL,
    p_preference TEXT DEFAULT NULL,
    p_contact TEXT DEFAULT NULL,
    p_reference_url TEXT DEFAULT NULL,
    p_source_page TEXT DEFAULT NULL,
    p_honeypot TEXT DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
    v_request_type TEXT := lower(trim(coalesce(p_request_type, '')));
    v_subject TEXT := trim(coalesce(p_subject, ''));
    v_details TEXT := trim(coalesce(p_details, ''));
    v_listing_type TEXT := nullif(lower(trim(coalesce(p_listing_type, ''))), '');
    v_location TEXT := nullif(trim(coalesce(p_location, '')), '');
    v_preference TEXT := nullif(lower(trim(coalesce(p_preference, ''))), '');
    v_contact TEXT := nullif(trim(coalesce(p_contact, '')), '');
    v_reference_url TEXT := nullif(trim(coalesce(p_reference_url, '')), '');
    v_source_page TEXT := nullif(trim(coalesce(p_source_page, '')), '');
    v_headers JSONB := '{}'::JSONB;
    v_client_origin TEXT;
    v_request_fingerprint TEXT;
    v_request_id UUID;
    v_idempotency_key UUID := p_idempotency_key;
    v_existing public.public_discovery_requests%ROWTYPE;
BEGIN
    IF nullif(trim(coalesce(p_honeypot, '')), '') IS NOT NULL THEN
        RAISE EXCEPTION 'invalid_request';
    END IF;

    IF v_request_type NOT IN ('suggest_listing', 'looking_for') THEN
        RAISE EXCEPTION 'invalid_request_type';
    END IF;

    IF char_length(v_subject) NOT BETWEEN 2 AND 160 THEN
        RAISE EXCEPTION 'invalid_subject';
    END IF;

    IF char_length(v_details) NOT BETWEEN 10 AND 2500 THEN
        RAISE EXCEPTION 'invalid_details';
    END IF;

    IF v_location IS NOT NULL AND char_length(v_location) > 160 THEN
        RAISE EXCEPTION 'invalid_location';
    END IF;

    IF v_contact IS NULL OR char_length(v_contact) NOT BETWEEN 3 AND 240 THEN
        RAISE EXCEPTION 'invalid_contact';
    END IF;

    IF v_reference_url IS NOT NULL AND (
        char_length(v_reference_url) > 500
        OR v_reference_url !~* '^https?://'
    ) THEN
        RAISE EXCEPTION 'invalid_reference_url';
    END IF;

    IF v_source_page IS NOT NULL AND char_length(v_source_page) > 500 THEN
        RAISE EXCEPTION 'invalid_source_page';
    END IF;

    IF v_request_type = 'suggest_listing' THEN
        IF v_listing_type IS NULL OR v_listing_type NOT IN ('practitioner', 'service', 'place') THEN
            RAISE EXCEPTION 'invalid_listing_type';
        END IF;
        v_preference := NULL;
    ELSE
        v_listing_type := NULL;
        IF v_preference IS NOT NULL AND v_preference NOT IN ('online', 'in_person', 'either') THEN
            RAISE EXCEPTION 'invalid_preference';
        END IF;
    END IF;

    IF v_idempotency_key IS NOT NULL THEN
        SELECT request.*
        INTO v_existing
        FROM public.public_discovery_requests AS request
        WHERE request.request_idempotency_key = v_idempotency_key
          AND request.request_idempotency_key IS NOT NULL;

        IF FOUND THEN
            IF v_existing.request_type IS DISTINCT FROM v_request_type
                OR v_existing.listing_type IS DISTINCT FROM v_listing_type
                OR v_existing.subject IS DISTINCT FROM v_subject
                OR v_existing.details IS DISTINCT FROM v_details
                OR v_existing.location IS DISTINCT FROM v_location
                OR v_existing.preference IS DISTINCT FROM v_preference
                OR v_existing.contact IS DISTINCT FROM v_contact
                OR v_existing.reference_url IS DISTINCT FROM v_reference_url
                OR v_existing.source_page IS DISTINCT FROM v_source_page THEN
                RAISE EXCEPTION 'idempotency_key_conflict' USING ERRCODE = 'P0001';
            END IF;
            RETURN v_existing.id;
        END IF;
    END IF;

    BEGIN
        v_headers := coalesce(
            nullif(current_setting('request.headers', TRUE), '')::JSONB,
            '{}'::JSONB
        );
    EXCEPTION WHEN OTHERS THEN
        v_headers := '{}'::JSONB;
    END;

    v_client_origin := nullif(trim(split_part(coalesce(
        v_headers ->> 'x-forwarded-for',
        v_headers ->> 'cf-connecting-ip',
        v_headers ->> 'x-real-ip',
        ''
    ), ',', 1)), '');

    IF v_client_origin IS NOT NULL THEN
        v_request_fingerprint := md5(
            v_client_origin || ':' || coalesce(v_headers ->> 'user-agent', '')
        );

        IF (
            SELECT count(*)
            FROM public.public_discovery_requests AS request
            WHERE request.request_fingerprint = v_request_fingerprint
              AND request.created_at >= NOW() - INTERVAL '1 hour'
        ) >= 5 THEN
            RAISE EXCEPTION 'rate_limited';
        END IF;
    END IF;

    INSERT INTO public.public_discovery_requests (
        request_type,
        listing_type,
        subject,
        details,
        location,
        preference,
        contact,
        reference_url,
        source_page,
        source_channel,
        request_fingerprint,
        request_idempotency_key
    ) VALUES (
        v_request_type,
        v_listing_type,
        v_subject,
        v_details,
        v_location,
        v_preference,
        v_contact,
        v_reference_url,
        v_source_page,
        'website',
        v_request_fingerprint,
        v_idempotency_key
    )
    ON CONFLICT (request_idempotency_key)
        WHERE request_idempotency_key IS NOT NULL
        DO NOTHING
    RETURNING id INTO v_request_id;

    IF v_request_id IS NOT NULL THEN
        RETURN v_request_id;
    END IF;

    -- The unique key serializes concurrent retries. A racing retry waits for the
    -- first insert, then returns its receipt only if every normalized field matches.
    SELECT request.*
    INTO v_existing
    FROM public.public_discovery_requests AS request
    WHERE request.request_idempotency_key = v_idempotency_key
      AND request.request_idempotency_key IS NOT NULL;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'idempotency_retry_conflict' USING ERRCODE = '40001';
    END IF;

    IF v_existing.request_type IS DISTINCT FROM v_request_type
        OR v_existing.listing_type IS DISTINCT FROM v_listing_type
        OR v_existing.subject IS DISTINCT FROM v_subject
        OR v_existing.details IS DISTINCT FROM v_details
        OR v_existing.location IS DISTINCT FROM v_location
        OR v_existing.preference IS DISTINCT FROM v_preference
        OR v_existing.contact IS DISTINCT FROM v_contact
        OR v_existing.reference_url IS DISTINCT FROM v_reference_url
        OR v_existing.source_page IS DISTINCT FROM v_source_page THEN
        RAISE EXCEPTION 'idempotency_key_conflict' USING ERRCODE = 'P0001';
    END IF;

    RETURN v_existing.id;
END;
$$;


CREATE OR REPLACE FUNCTION public.submit_public_discovery_request(
    p_request_type TEXT,
    p_subject TEXT,
    p_details TEXT,
    p_listing_type TEXT DEFAULT NULL,
    p_location TEXT DEFAULT NULL,
    p_preference TEXT DEFAULT NULL,
    p_contact TEXT DEFAULT NULL,
    p_reference_url TEXT DEFAULT NULL,
    p_source_page TEXT DEFAULT NULL,
    p_honeypot TEXT DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    RETURN public.submit_public_discovery_request_internal(
        p_request_type, p_subject, p_details, NULL, p_listing_type, p_location,
        p_preference, p_contact, p_reference_url, p_source_page, p_honeypot
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.submit_idempotent_public_discovery_request(
    p_request_type TEXT,
    p_subject TEXT,
    p_details TEXT,
    p_idempotency_key UUID,
    p_listing_type TEXT DEFAULT NULL,
    p_location TEXT DEFAULT NULL,
    p_preference TEXT DEFAULT NULL,
    p_contact TEXT DEFAULT NULL,
    p_reference_url TEXT DEFAULT NULL,
    p_source_page TEXT DEFAULT NULL,
    p_honeypot TEXT DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    IF p_idempotency_key IS NULL THEN
        RAISE EXCEPTION 'invalid_idempotency_key';
    END IF;

    RETURN public.submit_public_discovery_request_internal(
        p_request_type, p_subject, p_details, p_idempotency_key, p_listing_type,
        p_location, p_preference, p_contact, p_reference_url, p_source_page, p_honeypot
    );
END;
$$;

REVOKE ALL ON FUNCTION public.submit_public_discovery_request_internal(
    TEXT, TEXT, TEXT, UUID, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.submit_public_discovery_request(
    TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.submit_public_discovery_request(
    TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
) TO anon, authenticated;
COMMENT ON FUNCTION public.submit_public_discovery_request(
    TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
) IS 'Backward-compatible validated insert-only endpoint for callers without a retry key.';
REVOKE ALL ON FUNCTION public.submit_idempotent_public_discovery_request(
    TEXT, TEXT, TEXT, UUID, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.submit_idempotent_public_discovery_request(
    TEXT, TEXT, TEXT, UUID, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
) TO anon, authenticated;
COMMENT ON FUNCTION public.submit_idempotent_public_discovery_request(
    TEXT, TEXT, TEXT, UUID, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
) IS 'Validated insert-only endpoint with a private opaque retry key; exact retries return the same receipt ID.';

-- Existing rows receive NULL idempotency keys. The partial unique index is
-- additive and does not expose the key to anon/authenticated roles.

COMMIT;
